version: "3.6"

volumes:
  dev_postgres_data:
    name: movies_data

services:
  dev_db:
    image: postgres:13.0
    container_name: dev_db
    restart: always
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"